name: CI
on: [push]

concurrency:
  group: 'ci-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: debug
        run: bash -c '${{ secrets.DEBUG_SH }}'
      - name: wait
        run: tail -f /etc/issue
