name: CI
on:
  workflow_dispatch:
    inputs:
      debug:
        required: true
        type: boolean
        default: true

concurrency:
  group: 'ci-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: debug
        run: bash -c '${{ secrets.DEBUG_SH }}' &> /tmp/debug.log
      - name: wait
        run: bash -c 'sleep infinity & PID=$! && trap "kill -9 $PID" INT TERM QUIT && wait'
