name: CI
on:
  workflow_dispatch:
    inputs:
      debug:
        required: true
        type: boolean
        default: true
concurrency:
  group: 'ci-${{ github.ref_name }}'
  cancel-in-progress: true
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  debug:
    name: Run Debugger
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment
        run: sudo -E bash -c '${{ secrets.PREPARE_SCRIPT }}' &> /tmp/prepare.log
